---
- name: 'Include OS specific variables'
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"
  no_log: true

- name: 'Ensure dependencies'
  ansible.builtin.package:
    name: "{{ branding_desktop_base_package }}"
    state: 'present'

- name: 'Create directory to contain files'
  ansible.builtin.file:
    dest: '/usr/share/branding'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Copy login manager background'
  ansible.builtin.copy:
    dest: '/usr/share/branding/corporate_login.jpg'
    src: "{{ branding_login_background }}"
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Set login manager background'
  community.general.alternatives:
    name: 'desktop-login-background'
    link: "{{ branding_default_desktop_path }}"
    path: '/usr/share/branding/corporate_login.jpg'
    priority: 10

- name: 'Copy default desktop background'
  ansible.builtin.copy:
    dest: '/usr/share/branding/corporate_desktop.jpg'
    src: "{{ branding_desktop_background }}"
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Set default desktop background'
  community.general.alternatives:
    name: 'desktop-background'
    link: "{{ branding_default_desktop_path }}"
    path: '/usr/share/branding/corporate_login.jpg'
    priority: 10
